# Site settings
title: dev-iations
description: >
  the rants and deviations of a curious developer
url: http://marcosalles.github.io
blog_url: /blog

# Author settings
name: marco salles
email: marco.salles@gmail.com
phone: +5511 992.542.684

facebook_username: marcoacsalles
twitter_username: szzaass
github_username: marcosalles
linkedin_username: marcosalles

# Build settings
markdown: kramdown
