# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dev-iations
name: Marco Salles
email: marco.salles@gmail.com
description: >
  The rants and deviations of a curious developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marcosalles.github.io" # the base hostname & protocol for your site
twitter_username: szzaass
github_username:  marcosalles

# Build settings
markdown: kramdown
